version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/myapp/
    links:
      - php

  php:
    build: ./php
    links:
      - mysql
    volumes:
      - ./app:/var/www/myapp
    expose:
      - '9000'

  mysql:
    image: mysql:5.7.20
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
       - MYSQL_DATABASE=auction
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - '3306'

volumes:
  data-mysql: {}
